version: "3.6"
services:
  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ce
    restart: always
    hostname: gitlab
    network_mode: "host"
    volumes:
      ${USERDIR}/docker/gitlab/logs:/var/log/gitlab
      ${USERDIR}/docker/gitlab/data:/var/opt/gitlab
      ${USERDIR}/docker/gitlab/config:/etc/gitlab
    environment:
      - ROOT_PASSWORD=${ROOT_PASSWORD}
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

  mariadb:
    container_name: "mariadb"
    image: "linuxserver/mariadb"
    restart: always
    hostname: mariadb
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
        mode: host
    volumes:
      - ${USERDIR}/docker/mariadb:/config
    environment:
      - ROOT_PASSWORD=${ROOT_PASSWORD}
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    hostname: phpmyadmin
    links:
      - mariadb:db
    ports:
      - ${IP}:9001:80
    environment:
      - PMA_HOST=mariadb
      - ROOT_PASSWORD=${ROOT_PASSWORD}