version: "3.6"
services:
# Support Containers
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    command: --templates http://templates/templates.json
    ports:  # TODO add ipaddress hostip:hostport:containerport
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${USERDIR}/docker/portainer/data:/data
      - ${USERDIR}/docker/shared:/shared
    environment:
      - TZ=${TZ}

  # Watchtower monitors your Docker containers. If their images in the Docker Store
  # change, then watchtower will pull the new image, shutdown the running container
  # and restart with the new image and the options you originally set for the container
  # while deploying.
  watchtower:
    container_name: watchtower
    image: v2tec/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # --schedule "0 0 4 * * *" – containers are checked for updates at 4 am everyday.
    # You can use the 6-digit cron schedule or you can specify time interval:
    # --interval 30 for checking every 30 seconds. If you want weekly, then use
    # 0 0 23 * * SUN for every update at 11 pm on Sundays.
    command: --schedule "0 0 4 * * *" --cleanup

  organizr:
    container_name: organizr
    image: lsiocommunity/organizr
    restart: always
    volumes:
      - ${USERDIR}/docker/organizr:/config
      - ${USERDIR}/docker/shared:/shared
    ports: # TODO add ipaddress hostip:hostport:containerport
      - "80:80"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

  mariadb:
    container_name: "mariadb"
    image: "linuxserver/mariadb"
    restart: always
    hostname: mariadb
    volumes:
        - ${USERDIR}/docker/mariadb:/config
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
        mode: host
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
      - mariadb:db
    hostname: phpmyadmin
    ports:  # TODO add ipaddress hostip:hostport:containerport
      - 9001:80
    environment:
      - PMA_HOST=mariadb
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

  # For configeration see
  # https://www.smarthomebeginner.com/docker-home-media-server-2018-basic/#Smart_Home_Apps
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant
    restart: always
    # devices:
    #   - /dev/ttyUSB0:/dev/ttyUSB0
    #   - /dev/ttyUSB1:/dev/ttyUSB1
    #   - /dev/ttyACM0:/dev/ttyACM0
    volumes:
      - ${USERDIR}/docker/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}/docker/shared:/shared
    ports:  # TODO add ipaddress hostip:hostport:containerport hostip:hostport:containerport
      - "9002:8123"
    privileged: true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}


# Media Stuff

  # For configeration see
  # https://www.smarthomebeginner.com/docker-home-media-server-2018-basic/#Downloaders
  # transmission-vpn:
    # container_name: transmission-vpn
    # image: haugene/transmission-openvpn
    # restart: always
    # cap_add:
      # - NET_ADMIN
    # devices:
      # - /dev/net/tun
    # ports:
    # - "9003:9091"
    # dns:
      # - 1.1.1.1
      # - 1.0.0.1
    # volumes:
      # - /etc/localtime:/etc/localtime:ro
      # - ${USERDIR}/docker/transmission-vpn:/data
      # - ${USERDIR}/docker/shared:/shared
      # - ${USERDIR}/Downloads:/data/watch
      # - ${USERDIR}/Downloads/completed:/data/completed
      # - ${USERDIR}/Downloads/incomplete:/data/incomplete
    # environment:
      # - OPENVPN_PROVIDER=IPVANISH
      # - OPENVPN_USERNAME=ipvanish_username
      # - OPENVPN_PASSWORD=ipvanish_password
      # - OPENVPN_CONFIG="YYYYYYYYYYY" 
      # - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      # - LOCAL_NETWORK=192.168.1.0/24
      # - PUID=${PUID}
      # - PGID=${PGID}
      # - TZ=${TZ}
      # - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
      # - TRANSMISSION_RPC_HOST_WHITELIST="127.0.0.1,192.168.*.*"
      # - TRANSMISSION_RPC_PASSWORD=webui_password
      # - TRANSMISSION_RPC_USERNAME=webui_username
      # - TRANSMISSION_UMASK=002
      # - TRANSMISSION_RATIO_LIMIT=1.00
      # - TRANSMISSION_RATIO_LIMIT_ENABLED=true

  qbittorrent:
    container_name: "qbittorrent"
    image: "linuxserver/qbittorrent"
    restart: always
    volumes:
      - ${USERDIR}/docker/qbittorrent:/config
      - ${USERDIR}/Downloads/completed:/downloads
      - ${USERDIR}/docker/shared:/shared
    ports:  # TODO add ipaddress hostip:hostport:containerport
      - "9004:9004"
      - "6881:6881"
      - "6881:6881/udp"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=002
      - WEBUI_PORT=9004

  sabnzbd:
    container_name: "sabnzbd"
    image: "linuxserver/sabnzbd"
    restart: always
    volumes:
      - ${USERDIR}/docker/sabnzbd:/config
      - ${USERDIR}/Downloads/completed:/downloads
      - ${USERDIR}/Downloads/incomplete:/incomplete-downloads
      - ${USERDIR}/docker/shared:/shared
    ports:  # TODO add ipaddress hostip:hostport:containerport
        - "9005:8080"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

  radarr:
    container_name: "radarr"
    image: "linuxserver/radarr"
    restart: always
    volumes:
      - ${USERDIR}/docker/radarr:/config
      - ${USERDIR}/Downloads/completed:/downloads
      # TODO change media dir
      - ${USERDIR}/media/movies:/movies
      - "/etc/localtime:/etc/localtime:ro"
      - ${USERDIR}/docker/shared:/shared
    ports:  # TODO add ipaddress hostip:hostport:containerport
      - "9006:7878"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

  sonarr:
    container_name: "sonarr"
    image: "linuxserver/sonarr"
    restart: always
    volumes:
      - ${USERDIR}/docker/sonarr:/config
      - ${USERDIR}/Downloads/completed:/downloads
      # TODO change media dir
      - ${USERDIR}/media/tvshows:/tv
      - "/etc/localtime:/etc/localtime:ro"
      - ${USERDIR}/docker/shared:/shared
    ports:  # TODO add ipaddress hostip:hostport:containerport
        - "9007:8989"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

  plex:
    container_name: "plex"
    image: plexinc/pms-docker
    restart: always
    volumes:
      - ${USERDIR}/docker/plexms:/config
      # temporary folder for transcoding.
      - ${USERDIR}/Downloads/plex_tmp:/transcode
      # TODO Change media directory
      - /media/media:/media
      - ${USERDIR}/docker/shared:/shared
    ports:  # TODO add ipaddress hostip:hostport:containerport
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    environment:
      - TZ=${TZ}
      - HOSTNAME="Docker Plex"
      - PLEX_CLAIM="claim-x5RqoT5zRdk5yHfd5iBb"
      - PLEX_UID=${PUID}
      - PLEX_GID=${PGID}
      - ADVERTISE_IP="http://192.168.1.122:32400/"

  # Monitoring Plex Usage
  tautulli:
    container_name: tautulli
    image: linuxserver/tautulli
    restart: always
    volumes:
      - ${USERDIR}/docker/tautulli/config:/config
      - ${USERDIR}/docker/tautulli/logs:/logs:ro
      - ${USERDIR}/docker/shared:/shared
    ports:  # TODO add ipaddress hostip:hostport:containerport
      - "9008:8181"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

  #  Ombi allows you to accept Movie or TV Show requests from friends and family.
  ombi:
    container_name: ombi
    image: linuxserver/ombi
    restart: always
    volumes:
      - ${USERDIR}/docker/ombi:/config
      - ${USERDIR}/docker/shared:/shared
    ports:  # TODO add ipaddress hostip:hostport:containerport
      - "9009:3579"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

  # Hydra is a meta search for NZB indexers
  hydra:
    container_name: "hydra"
    image: "linuxserver/hydra"
    restart: always
    volumes:
      - ${USERDIR}/docker/hydra:/config
      - ${USERDIR}/Downloads:/downloads
      - ${USERDIR}/docker/shared:/shared
    ports:  # TODO add ipaddress hostip:hostport:containerport
      - "9010:5075"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ} 
  
  # Jackett is a proxy server that translates search queries from apps such as SickRage,
  # CouchPotato, Sonarr, Mylar, Radarr, etc. into torrent tracker-site-specific HTTP
  # queries.
  jackett:
    container_name: "jackett"
    image: "linuxserver/jackett"
    restart: always
    volumes:
      - ${USERDIR}/docker/jackett:/config
      - ${USERDIR}/Downloads/completed:/downloads
      - "/etc/localtime:/etc/localtime:ro"
      - ${USERDIR}/docker/shared:/shared
    ports:  # TODO add ipaddress hostip:hostport:containerport
      - "9011:9117"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}