version: "3.7"
services:
  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ce
    restart: always
    hostname: gitlab
    # TODO: need a better network mode
    network_mode: "host"
    volumes:
      ${CONTAINERDIR}/gitlab/logs:/var/log/gitlab
      ${CONTAINERDIR}/gitlab/data:/var/opt/gitlab
      ${CONTAINERDIR}/gitlab/config:/etc/gitlab
    environment:
      - ROOT_PASSWORD=${ROOT_PASSWORD}
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}