version: "2"
services:
  gitlab:
    image: gitlab/gitlab-ce
    restart: always
    container_name: gitlab
    hostname: 'git.bitterpilot.org'
    networks:
      qnet-static:
        ipv4_address: 192.168.1.5
    volumes:
      - /share/CACHEDEV3_DATA/containerData/gitlab/logs:/var/log/gitlab
      - /share/CACHEDEV3_DATA/containerData/gitlab/data:/var/opt/gitlab
      - /share/CACHEDEV3_DATA/containerData/gitlab/config:/etc/gitlab

networks:
  qnet-static:
    driver: qnet
    ipam:
      driver: qnet
      options:
        iface: "eth1"
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1