version: '3'
services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     networks:
       - service
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: ${MYSQL_DATABASE_PASSWORD}

   wordpress:
     image: wordpress:latest
     volumes:
       - wp_data:/var/www/html
     networks:
       - service
     ports:
       - 80
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
       
   phpmyadmin:
     image: phpmyadmin/phpmyadmin
     hostname: phpmyadmin
     networks:
       - service
     ports:
       - 80
     environment:
       PMA_HOST: db:3306
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       
volumes:
    db_data:
    wp_data:

networks:
  service:
    driver: overlay