version: "3.6"
services:
# Support Containers

# container managment
  portainer:
    container_name: Portainer
    image: portainer/portainer
    restart: always
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CONTAINERDIR}/portainer/data:/data
      - ${CONTAINERDIR}/shared:/shared
    environment:
      - TZ=${TZ}

  # Watchtower monitors your Docker containers. If their images in the Docker Store
  # change, then watchtower will pull the new image, shutdown the running container
  # and restart with the new image and the options you originally set for the container
  # while deploying.
  watchtower:
    container_name: Watchtower
    image: v2tec/watchtower
    restart: always
    network_mode: "none"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # --schedule "0 0 4 * * *" – containers are checked for updates at 4 am everyday.
    # You can use the 6-digit cron schedule or you can specify time interval:
    # --interval 30 for checking every 30 seconds. If you want weekly, then use
    # 0 0 23 * * SUN for every update at 11 pm on Sundays.
    command: --schedule "0 0 4 * * *" --cleanup

# 
  organizr:
    container_name: Organizr
    image: lsiocommunity/organizr
    restart: always
    ports:
      - 80:80
    volumes:
      - ${CONTAINERDIR}/organizr/config:/config
      - ${CONTAINERDIR}/shared:/shared
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

  bind:
    container_name: Bind_DNS
    image: sameersbn/bind
    ports:
      - 10000:10000
      - 10022:202
      - 53:503
      - 53:53/udp
    volumes:
      - ${CONTAINERDIR}/bind:/data/bind/etc
      - ${CONTAINERDIR}/shared:/shared
    environment:
      - ROOT_PASSWORD=${ROOT_PASSWORD}

  steamcache:
    container_name: Steam_Cache
    image: steamcache/steamcache
    restart: always
    hostname: SteamCache
    network_mode: host
    ports:
      - 80:80
    volumes:
      - ${CONTAINERDIR}/steamCache/logs:/data/logs
      - ${CONTAINERDIR}/steamCache/cache:/data/cache
      - ${CONTAINERDIR}/steamCache/www:/var/www
      - ${CONTAINERDIR}/shared:/shared