# check this
# https://www.thepolyglotdeveloper.com/2017/03/nginx-reverse-proxy-containerized-docker-applications/
version: "3"
services:
  proxy:
    container_name: proxy
    image: nginx
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "./ssl.conf:/etc/nginx/ssl.conf"
      - "./certs:/etc/ssl/private"
      - "/var/run/codeserver.sock:/var/run/codeserver.sock"
    ports:
        - 80:80
        - 443:443
    restart: unless-stopped
  
  StaticSite_www:
    container_name: StaticSite_www
    image: www.bitterpilot.org
    restart: unless-stopped
