version: '3.7'
services:
  portainer:
    image: portainer/portainer
    ports:
      - 9000:9000
    networks:
      - portainer_agent
    volumes:
      - portainer:/data
      - portainer:/shared

      
  agent:
    image: portainer/agent
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - target: 9001
        published: 9001
        protocol: tcp
        mode: host
    networks:
      - portainer_agent
    deploy:
      mode: global

networks:
  portainer_agent:
    driver: overlay
    
volumes:
  portainer:

